### ISSUE TITLE
NR spits this error after every deploy despite being properly configured/working

### ISSUE THREAD

**Issue by obaldius** [mattdavis90/node-red-contrib-tado-client#57] opened 2023-11-04 22:24 UTC
Little else to be said:

![image](https://github.com/mattdavis90/node-red-contrib-tado-client/assets/61756214/3478d9f8-ddb1-496e-93fb-0773dea14a27)
![image](https://github.com/mattdavis90/node-red-contrib-tado-client/assets/61756214/469d817e-2daf-4d58-a4cc-41ac397a59f7)

**Comment by mattdavis90** [comment] 2023-11-04 23:04
Hi,

I've only seen this when a username/password hasn't been configured but since you say it is working that seems unlikely. Can you provide more information? Such as;

What version of NodeRed are you using?
What version of the library is installed?
What version of node.js is running?
Can you provide an export of the flow you're running?
Can you provide a screenshot of the node that is causing issues?

Please remove any personal information from screenshots and exports.

**Comment by Brewj** [comment] 2023-11-05 09:11
You don't by chance have two configurations within your Tado node do you? The one working but a second incomplete?

**Comment by michael-borkowski** [comment] 2023-11-06 10:09
Hi, I have the same issue as of recently (noticed it randomly today, don't know which version this appeared in).

I didn't chagne anything with my username/password configuration so everything should be fine there.

One more thing I can add is this screenshot:

![Screenshot from 2023-11-06 10-03-01](https://github.com/mattdavis90/node-red-contrib-tado-client/assets/3902156/47faa949-6829-4d13-98ca-6a4aca1aa93d)

My details:

* Node-RED v3.1.0
* Node.js v16.20.2
* node-red-contrib-tado-client v0.10.7
* Nothing in the logs :(
* All tado nodes are affected by this, even without a proper config (in that case, they complain about both the missing config and the "invalid number")
* However, the nodes' functionality is not affected: They still work!

I'm happy to provide more help.

**Comment by mattdavis90** [comment] 2023-11-06 18:02
Hi, thanks for the extra information. That's really helpful. I'll go through each of the recent versions on a clean set up and see if I can work out where this got introduced.

**Comment by michael-borkowski** [comment] 2023-11-07 09:28
Thank you so much for your help. Again, if I can be of any help, please let me know. I'm happy to test debug versions too.

**Comment by mattdavis90** [comment] 2023-11-08 20:26
I worked out the issue. When the new property for updating energy usage was added a number validator was put on the property. It looks as though NodeRed doesn't retrospectively update node's configs to include default values so `undefined` was left in-place. The number validator then errors saying that isn't a number. I'm updated the validation function to accept undefined or a number which seems to have fixed the issue locally for me. If you update to v0.10.8 then the little red signs should go away

**Comment by michael-borkowski** [comment] 2023-11-08 21:23
Thank you so much for looking into this so fast! Interestingly, it hasn't gone away but was replaced by a different message:

![Screenshot 2023-11-08 212129](https://github.com/mattdavis90/node-red-contrib-tado-client/assets/3902156/d9600dde-9865-406b-8632-bd8fc0e7cb35)

Note that this node uses "Get the Current User" which doesn't have the settings that the message is complaining about. This, again, appears on all nodes, regardless of which function they actually use.

Let me know if I can help in any way - thanks!

**Comment by mattdavis90** [comment] 2023-11-08 21:31
Looks like I copy and pasted very poorly from my dev setup to the repo and somhow missed

**Comment by mattdavis90** [comment] 2023-11-08 21:45
I've just updated my live NodeRed setup from npm and it appears to have fixed correctly for me. If @michael-borkowski you can confirm that would be awesome. Didn't mean to close the issue earlier, hit the wrong comment button

**Comment by michael-borkowski** [comment] 2023-11-09 07:53
I can confirm this fixed the issue *but* for some reason exactly one node - the node I was looking at on v0.10.8 - was the only one with the red triangle still there after the update to v0.10.9. It only complained about `tariffInCents`. Since all the other nodes were fine, I just re-created it (had to do so from scratch - copying the node also copied the red triangle).

I suppose this has something to do with my attempts at v0.10.8, since no other nodes were affected. Perhaps something in that version "broke" the node in some way? Not sure if you want to just leave this as-is, assuming that the number of people who used v0.10.8 in that short time frame is low, or if you want to introduce code to more gracefully un-break nodes - In any case, this is the current node state of the node:

```
[
    {
        "id": "d47b3fae18a98482",
        "type": "tado",
        "z": "80c0daf0d6dc14e8",
        "configName": "ddfe6badbb177330",
        "apiCall": "getMe",
        "homeId": "",
        "acMode": "AUTO",
        "deviceId": "",
        "fanSpeed": "AUTO",
        "geoTracking": true,
        "name": "",
        "openWindowMode": true,
        "power": "on",
        "presence": "HOME",
        "reading": "",
        "readingDate": "",
        "readingId": "",
        "reportDate": "",
        "startDate": "",
        "endDate": "",
        "tariffId": "",
        "tariffInCents": "",
        "temperature": "18",
        "temperatureOffset": 0,
        "terminationTimeout": 900,
        "terminationType": "manual",
        "timetableId": "",
        "windowDetection": true,
        "windowDetectionTimeout": 900,
        "zoneId": "",
        "x": 450,
        "y": 1000,
        "wires": [
            []
        ]
    },
    {
        "id": "ddfe6badbb177330",
        "type": "tado-config",
        "name": "mic***@***.***"
    }
]
```

Again, thanks so much for the quick response, and for all your work overall! This extension has been incredibly valuable and I am using it very happily :)

**Comment by mattdavis90** [comment] 2023-11-09 07:59
Great to hear it's working. I had that issue with one of mine as well. I changed the API call to one that displays the tariff and change the empty string to a 0. I'll have a think and a Google around how to better handle upgrading the properties on a node. I'm sure this must be something that is documented.

No problem at all, I'm glad it works for you and is helpful.

**Closed by mattdavis90** 2023-11-09 07:59 UTC

**Comment by mattdavis90** [comment] 2023-11-09 08:03
I've opened #58 to cover the property upgrading work
