### ISSUE TITLE
Simple help question

### ISSUE THREAD

**Issue by madradrakie** [mattdavis90/node-red-contrib-tado-client#38] opened 2021-08-30 19:14 UTC
Hello,

I'am trying to get the tado client working but need some help. 

I'am simply trying to set the temperature for a specific device but it is not working. I configured the tado node with the home id and selected the function **Set a zone's overlay.**. I also configured the other requested data. 
The input message to trigger the node contains the following code:

msg.payload
J:
{
    "setting": {
    "type": "HEATING",
    "power": "ON",
    "temperature": {
        "celsius": 21
                    }
                }
}

Unfortanuatly, the temperate as set in the node itself is send tot the tado and not the information as inputed in the input. 
Does anybody knows what i am doing wrong?

Thanks in advance.

**Comment by mattdavis90** [comment] 2021-08-31 19:34
Hi, thanks for using the library. The node expects that the parameters are set in the top level of the `msg` object. Something like
```json
{
    "power": "ON",
    "temperature": 21
}
```

should achieve what you're after.

**Comment by madradrakie** [comment] 2021-09-01 16:56
Thanks Matt for your answer. Unfortunately it is still not working. Could
you maybe send an example of how your flow is working?


[image: image.png]



[image: image.png]

Op di 31 aug. 2021 om 21:35 schreef Matt Davis ***@***.***>:

**Comment by mattdavis90** [comment] 2021-09-01 18:26
Hi madradrakie, the issue is that you're putting the content into `msg.payload` instead of `msg` and the structure is slightly incorrect. The example I showed above should work on an inject node but for completeness here is a flow that should work if you enter your Tado credentials. Hope this helps.

```json
[
    {
        "id": "e587f42f7616fa77",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "c844438ffd15c67d",
        "type": "inject",
        "z": "e587f42f7616fa77",
        "name": "",
        "props": [
            {
                "p": "temperature",
                "v": "21",
                "vt": "num"
            },
            {
                "p": "power",
                "v": "on",
                "vt": "str"
            },
            {
                "p": "type",
                "v": "heating",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "x": 80,
        "y": 140,
        "wires": [
            [
                "bd2fc0ae5834348b"
            ]
        ]
    },
    {
        "id": "bd2fc0ae5834348b",
        "type": "tado",
        "z": "e587f42f7616fa77",
        "configName": "d1cf260f.0bb368",
        "apiCall": "setZoneOverlay",
        "homeId": "1234",
        "deviceId": "",
        "zoneId": "1",
        "power": "on",
        "temperature": "18",
        "terminationType": "manual",
        "terminationTimeout": 900,
        "name": "",
        "reportDate": "",
        "presence": "HOME",
        "geoTracking": true,
        "temperatureOffset": 0,
        "windowDetection": true,
        "windowDetectionTimeout": 900,
        "openWindowMode": true,
        "timetableId": "",
        "x": 230,
        "y": 140,
        "wires": [
            [
                "feafedd1d240c031"
            ]
        ]
    },
    {
        "id": "feafedd1d240c031",
        "type": "debug",
        "z": "e587f42f7616fa77",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 390,
        "y": 140,
        "wires": []
    },
    {
        "id": "d1cf260f.0bb368",
        "type": "tado-config",
        "name": ""
    }
]
```

**Comment by madradrakie** [comment] 2021-09-07 18:39
and another simple question but i can not figure it out. How do i set the inject node to msg. The only option i have is msg.(someyhing). When i delete **payload** , the inject node is not working. Thanks again for helping me out..... (i'am still learning nodered every day ;-))

![image](https://user-images.githubusercontent.com/55043830/132394592-772d8eb8-4403-49cf-90a8-752657a46809.png)

**Comment by mattdavis90** [comment] 2021-09-07 19:12
Hi,

If you use the add button (near the bottom of the panel) to create 3 fields; name them power, temperature, and type.
Then set them to string, number, and string respectively.
Then add in the values it should work. You should end up with something like the following.

![Screenshot-20210907200847-589x819](https://user-images.githubusercontent.com/4218833/132398362-cedaa73a-73b2-4867-acda-9c6facd8b1f4.png)

**Comment by madradrakie** [comment] 2021-09-07 19:23
wow, that was super simple! Thank you for your patience and help. It is working! 👍

**Comment by mattdavis90** [comment] 2021-09-07 19:34
No problem. Glad I could help and glad you're using the library. Let me know if there's anything else. I'll close this for now.

**Closed by mattdavis90** 2021-09-07 19:34 UTC
