### ISSUE TITLE
Only 1 node available in Node-Red

### ISSUE THREAD

**Issue by JanLankhorst** [mattdavis90/node-red-contrib-tado-client#3] opened 2019-07-17 06:04 UTC
Hi,

After installing in Node_Red I only have the Tado node... The Tado-Config node is not available. Any clues on how to solve that?

Thanks.
Jan

**Comment by mattdavis90** [comment] 2019-07-21 15:45
Hi Jan,

Sorry for taking a while to get back. I'm not able to replicate the issue. Could you provide more information on how you installed the add-on?

When I install from using the built in add-on manager I get a Tado node in the pallette. When you add the node you should be able to configure the Tado loging details, this will automatically add a config node. Is this behaviour the same for you?

Thanks,
Matt

**Comment by mattdavis90** [comment] 2019-08-03 08:41
Hi Jan, Are you still having issues or can I close this now? Thanks

**Comment by mattdavis90** [comment] 2019-08-28 15:16
Closing this due to inactivity

**Closed by mattdavis90** 2019-08-28 15:16 UTC

**Comment by sniperxnl** [comment] 2022-11-02 11:09
i installed it also today, and get the message installed TADO and TADO-CONFIG pallette, but only see under heating only TADO

**Comment by mattdavis90** [comment] 2022-11-02 21:06
Hi @sniperxnl ,

This is expected behaviour. The `Tado` node is the main node that allows you to interact with the Tado API and the `Tado Config` node won't appear in the palette until you create a configuration. If you add the `Tado` node to a flow then double click it you should be able to create a new config with the little edit button. Hopefully this image helps.

![Screenshot-20221102210129-629x228](https://user-images.githubusercontent.com/4218833/199602451-ee306dbe-73de-42c8-a36b-2c1331105a69.png)

Thanks

**Comment by sniperxnl** [comment] 2022-11-03 08:29
I have done that, with my email and password, and deploy it. But after 10 minuts still no extra palette and get not data when i attach a msg.payload to it.

**Comment by mattdavis90** [comment] 2022-11-03 19:38
Hi,

The config node doesn't appear in the palette even once configured - this is a feature of NodeRed. They will show in the sidebar to the right under the config tab though (the little cog).

The Tado node doesn't do anything until you send a message into it. If you add an `inject` node to the input side of the Tado node then you can trigger the API call. The documentation attached to the node may help with all the different options available.

![Screenshot-20221103193547-540x71](https://user-images.githubusercontent.com/4218833/199817697-267cb0af-0d6a-4564-b1b7-e2d70e31d1f9.png)

Alternatively, this should work if you import it

```json
[{"id":"f5a80594728546d9","type":"tab","label":"Flow 2","disabled":false,"info":"","env":[]},{"id":"56b8c69fc98055fd","type":"inject","z":"f5a80594728546d9","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":100,"y":140,"wires":[["4ced7d39813d847a"]]},{"id":"d598f97ed3caa3ad","type":"debug","z":"f5a80594728546d9","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":410,"y":140,"wires":[]},{"id":"4ced7d39813d847a","type":"tado","z":"f5a80594728546d9","configName":"d1cf260f.0bb368","apiCall":"getMe","homeId":"","deviceId":"","zoneId":"","power":"on","temperature":"18","terminationType":"manual","terminationTimeout":900,"fanSpeed":"AUTO","acMode":"AUTO","name":"","reportDate":"","presence":"HOME","geoTracking":true,"temperatureOffset":0,"windowDetection":true,"windowDetectionTimeout":900,"openWindowMode":true,"timetableId":"","x":250,"y":140,"wires":[["d598f97ed3caa3ad"]]},{"id":"d1cf260f.0bb368","type":"tado-config","name":""}]
```
